### ISSUE TITLE
Create Docker-based workflow to generate model

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#297] opened 2020-05-15 14:54 UTC
The current problem is that models are not easy to reproduce given that it depends on what data the user downloads, what version of ADS, etc. To mitigate the issue, the idea is to create a Dockerfile that will enable to create a model. More specifically, the specs are:
- Dockerfile will:
  - Download the data from OSF with wget
  - git clone and checkout a specific version of ADS
  - create a config file for training
  - run training
  - package model and log file (note: log file should include info about hardware)
- Upload model to OSF
- Update wiki + doc

The Docker image could be uploaded on dockerhub, and/or we could save the Dockerfile in the ADS repos under specific folder e.g. docker/Dockerfile_train_SEM

Refs:
- https://github.com/Deep-MI/FatSegNet

Related to https://github.com/neuropoly/axondeepseg/issues/283

**Comment by mathieuboudreau** [comment] 2020-05-28 19:29
I created a branch for this issue: [`docker`](https://github.com/neuropoly/axondeepseg/tree/docker)

I created a Dockerfile (for CPU use) in that branch: https://github.com/neuropoly/axondeepseg/blob/docker/Dockerfile

I based the Dockerfile from another one of my projects, so there might be several installation packages that could be removed and/or a smaller base image could be used.

I ran it in Docker on my local computer by doing the following:

* Downloading, installing, and signing it to Docker: https://docs.docker.com/get-docker/
* Installing `repo2docker` (`pip install jupyter-repo2docker`)
* Ran `repo2docker` for that branch: repo2docker --ref docker https://github.com/neuropoly/axondeepseg

I then opened loaded Jupyter in a browser (using the link given to me in the terminal after running repo2docker), opened up a terminal, and ran the unit tests (`py.test --cov AxonDeepSeg/ --cov-report term-missing`), and they all passed:

<img width="1440" alt="Capture d’écran 2020-05-28 à 16 50 31" src="https://user-images.githubusercontent.com/1421029/83184643-5074e280-a104-11ea-8da2-cdc92518902c.png">

To do next:

* [ ] Try the same procedure but remotely from `bireli`.
  * [ ] Run the unit tests
* [ ] Modify Dockerfile and/or docker commands to use GPU for training.
  * [ ] Run the unit tests again
  * [ ] Run our Jupyter Notebooks
* [ ] Once setup can run GPU training, export/save Docker images after training an SEM and TEM model
* [ ] Decide on where to host the Docker images (Dockerhub? Duke?)

**Comment by mariehbourget** [comment] 2020-05-28 19:53
Thanks @mathieuboudreau  for helping me starting this!
I'll try it on my station, do the next steps on bireli and let you know if I have questions.

**Comment by mariehbourget** [comment] 2020-05-29 16:47
@mathieuboudreau 
All the tests are passing on my station (CPU) and I'm able to execute every notebooks except the training part (1.4) of the 02-training_gudeline.ipynb
The first time I tried, I had this error:

![01-Screen Shot 2020-05-29 at 12 35 51 PM](https://user-images.githubusercontent.com/54086142/83284162-56250380-a1aa-11ea-800d-33a47df73e86.png)

The second time after the restart of the kernel:

![02-Screen Shot 2020-05-29 at 12 36 38 PM](https://user-images.githubusercontent.com/54086142/83284169-5c1ae480-a1aa-11ea-9946-63d151a346da.png)

**Comment by mariehbourget** [comment] 2020-05-29 18:43
Yes I have. From what I gathered, it is a warning and means that tensorflow is not optimized for my CPU but should work anyway. Mathieu asked me the screenshot of the errors as usually I am able to train locally on my CPU (outside of docker).
I double-checked and the same error line about CPU support instructions appears when training locally.
![Screen Shot 2020-05-29 at 2 27 28 PM](https://user-images.githubusercontent.com/54086142/83294084-b328b580-a1ba-11ea-847b-9c54498b684f.png)

I haven't found meaningful info on the `XLA service 0x565277336ad0 executing computations on platform Host. Devices:` and `StreamExecutor device (0): <undefined>, <undefined>` line yet, but it looks like the docker container doesn't see/use the CPU.

**Comment by mariehbourget** [comment] 2020-06-04 20:52
@mathieuboudreau 
I'm unable to run repo2docker on bireli.
Docker is installed correctly and the service is running,
```
systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-05-14 10:24:30 EDT; 3 weeks 0 days ago
     Docs: https://docs.docker.com
 Main PID: 2360 (dockerd)
    Tasks: 27
   Memory: 139.9M
      CPU: 10min 3.003s
   CGroup: /system.slice/docker.service
           └─2360 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```
but I have permission problems with repo2docker.
```
repo2docker --ref docker https://github.com/neuropoly/axondeepseg
Docker client initialization error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied')).
Check if docker is running on the host.
```

I think it's because docker has to be run as sudo.
I don't know how to move forward from here, do you have an idea?

**Comment by jcohenadad** [comment] 2020-06-09 15:35
@mariehbourget maybe you need to set credentials to be able to write on dockerhub, see https://github.com/ansible/ansible-container/issues/761#issuecomment-335161450

**Comment by mathieuboudreau** [comment] 2020-06-09 16:25
To me it looks like the error I get when I forget to open the Docker app or log in - there might ve a way to chexk to see if it's running in the background (on my Mac I just see an app icon)

**Comment by mariehbourget** [comment] 2020-06-11 16:06
I'm not sure what the login part is.
On my Mac, Docker Desktop is running, I haven't sign in to anything and repo2docker works fine.
On bireli, the docker service is running : `sudo systemctl is-active docker` returns `active` but permissions are denied for repo2docker.

Because docker has to be run as sudo on bireli, I think the solution proposed by Julien (add user to docker group) would do the trick. However, in my search, I found [this](https://medium.com/@suixo/linux-users-running-docker-without-sudo-is-dangerous-3e5c5654abea) and [this](https://docs.docker.com/engine/install/linux-postinstall/). It seems that adding the user to the group could be a problem for security.

**Comment by dyt811** [comment] 2021-03-21 02:49
Could someone comment on the long term interest in this? I am trying to gauge the necessity/interest to have dockized deployment process for all main repos. Current GitHub Action ADS PyTest model could be adapted easily to handle a Docker based installation via Dockerfile, in addition to the existing effort above, would enhance the long term reproducibility on versioned ADS docker images once stashed at DockerHub etc. 

This becomes INCREASINGLY relevant as now [WSL2 will finally start supporting GPU through Docker](https://www.docker.com/blog/wsl-2-gpu-support-is-here/) allowed vast majority of Windows user to leverage GPU via Docker without gazillion hoops to jump through.

**Comment by mathieuboudreau** [comment] 2021-03-21 12:35
I can't speak for a long term interest (in particular, the setup might change once we migrate to IVADOMED), however I agree that I think this will be super important to be reproducible in the future. I don't know about the Windows side of things, as I think this was mostly for us to internally reproduce model training & generations; we (I) don't expect many users to generate their own models outside of our lab.

**Comment by jcohenadad** [comment] 2021-03-22 01:03
Agreed with @mathieuboudreau, we should probably think of a smart strategy to test/generate models without duplicating our efforts across SCT/ivadomed/ADS. Centralizing model-specific tests under ivadomed sounds like a wiser approach i think. 

also, i agree with @mathieuboudreau, at this point, most of our users do not train models (we do). But yeah... ultimately, users _should_ be able to do that (in fact, we already had some users who wanted to do it...)

**Comment by mathieuboudreau** [comment] 2024-12-11 15:31
Closing, duplicate of #616

**Closed by mathieuboudreau** 2024-12-11 15:31 UTC
Labels: feature, ci
